// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/workflow.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartbeatTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatTaskRequest) Reset() {
	*x = HeartbeatTaskRequest{}
	mi := &file_api_proto_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatTaskRequest) ProtoMessage() {}

func (x *HeartbeatTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatTaskRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *HeartbeatTaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type HeartbeatTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatTaskResponse) Reset() {
	*x = HeartbeatTaskResponse{}
	mi := &file_api_proto_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatTaskResponse) ProtoMessage() {}

func (x *HeartbeatTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatTaskResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatTaskResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type RegisterWorkflowRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Namespace             string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	WorkflowType          string                 `protobuf:"bytes,2,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	Steps                 []string               `protobuf:"bytes,3,rep,name=steps,proto3" json:"steps,omitempty"`
	CompensationSteps     []string               `protobuf:"bytes,4,rep,name=compensation_steps,json=compensationSteps,proto3" json:"compensation_steps,omitempty"`
	DefaultTimeoutSeconds int32                  `protobuf:"varint,5,opt,name=default_timeout_seconds,json=defaultTimeoutSeconds,proto3" json:"default_timeout_seconds,omitempty"`
	StepMaxAttempts       []int32                `protobuf:"varint,6,rep,packed,name=step_max_attempts,json=stepMaxAttempts,proto3" json:"step_max_attempts,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RegisterWorkflowRequest) Reset() {
	*x = RegisterWorkflowRequest{}
	mi := &file_api_proto_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkflowRequest) ProtoMessage() {}

func (x *RegisterWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkflowRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterWorkflowRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RegisterWorkflowRequest) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *RegisterWorkflowRequest) GetSteps() []string {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *RegisterWorkflowRequest) GetCompensationSteps() []string {
	if x != nil {
		return x.CompensationSteps
	}
	return nil
}

func (x *RegisterWorkflowRequest) GetDefaultTimeoutSeconds() int32 {
	if x != nil {
		return x.DefaultTimeoutSeconds
	}
	return 0
}

func (x *RegisterWorkflowRequest) GetStepMaxAttempts() []int32 {
	if x != nil {
		return x.StepMaxAttempts
	}
	return nil
}

type RegisterWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkflowResponse) Reset() {
	*x = RegisterWorkflowResponse{}
	mi := &file_api_proto_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkflowResponse) ProtoMessage() {}

func (x *RegisterWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkflowResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterWorkflowResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterWorkflowResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterWorkflowResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type StartWorkflowRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Namespace      string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Input          []byte                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	TaskQueue      string                 `protobuf:"bytes,3,opt,name=task_queue,json=taskQueue,proto3" json:"task_queue,omitempty"`
	TimeoutSeconds int64                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartWorkflowRequest) Reset() {
	*x = StartWorkflowRequest{}
	mi := &file_api_proto_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkflowRequest) ProtoMessage() {}

func (x *StartWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkflowRequest.ProtoReflect.Descriptor instead.
func (*StartWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *StartWorkflowRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *StartWorkflowRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *StartWorkflowRequest) GetTaskQueue() string {
	if x != nil {
		return x.TaskQueue
	}
	return ""
}

func (x *StartWorkflowRequest) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type StartWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkflowResponse) Reset() {
	*x = StartWorkflowResponse{}
	mi := &file_api_proto_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkflowResponse) ProtoMessage() {}

func (x *StartWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkflowResponse.ProtoReflect.Descriptor instead.
func (*StartWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *StartWorkflowResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StartWorkflowResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *StartWorkflowResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StartWorkflowResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type StreamTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskQueue     string                 `protobuf:"bytes,2,opt,name=task_queue,json=taskQueue,proto3" json:"task_queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTasksRequest) Reset() {
	*x = StreamTasksRequest{}
	mi := &file_api_proto_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTasksRequest) ProtoMessage() {}

func (x *StreamTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTasksRequest.ProtoReflect.Descriptor instead.
func (*StreamTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *StreamTasksRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *StreamTasksRequest) GetTaskQueue() string {
	if x != nil {
		return x.TaskQueue
	}
	return ""
}

type HistoryEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ActivityName  string                 `protobuf:"bytes,3,opt,name=activity_name,json=activityName,proto3" json:"activity_name,omitempty"`
	Result        []byte                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryEvent) Reset() {
	*x = HistoryEvent{}
	mi := &file_api_proto_workflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryEvent) ProtoMessage() {}

func (x *HistoryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryEvent.ProtoReflect.Descriptor instead.
func (*HistoryEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_workflow_proto_rawDescGZIP(), []int{7}
}

func (x *HistoryEvent) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *HistoryEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *HistoryEvent) GetActivityName() string {
	if x != nil {
		return x.ActivityName
	}
	return ""
}

func (x *HistoryEvent) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type StreamTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Input         []byte                 `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	StepName      string                 `protobuf:"bytes,5,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	StepIndex     int32                  `protobuf:"varint,6,opt,name=step_index,json=stepIndex,proto3" json:"step_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTaskResponse) Reset() {
	*x = StreamTaskResponse{}
	mi := &file_api_proto_workflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTaskResponse) ProtoMessage() {}

func (x *StreamTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTaskResponse.ProtoReflect.Descriptor instead.
func (*StreamTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_workflow_proto_rawDescGZIP(), []int{8}
}

func (x *StreamTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StreamTaskResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *StreamTaskResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreamTaskResponse) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *StreamTaskResponse) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *StreamTaskResponse) GetStepIndex() int32 {
	if x != nil {
		return x.StepIndex
	}
	return 0
}

type CompleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Result        []byte                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskRequest) Reset() {
	*x = CompleteTaskRequest{}
	mi := &file_api_proto_workflow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskRequest) ProtoMessage() {}

func (x *CompleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workflow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskRequest.ProtoReflect.Descriptor instead.
func (*CompleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workflow_proto_rawDescGZIP(), []int{9}
}

func (x *CompleteTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CompleteTaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *CompleteTaskRequest) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CompleteTaskRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CompleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskResponse) Reset() {
	*x = CompleteTaskResponse{}
	mi := &file_api_proto_workflow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskResponse) ProtoMessage() {}

func (x *CompleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workflow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskResponse.ProtoReflect.Descriptor instead.
func (*CompleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_workflow_proto_rawDescGZIP(), []int{10}
}

func (x *CompleteTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CompensationTaskResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TaskId               string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkflowId           string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Name                 string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Input                []byte                 `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	StepName             string                 `protobuf:"bytes,5,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	CompensationStepName string                 `protobuf:"bytes,6,opt,name=compensation_step_name,json=compensationStepName,proto3" json:"compensation_step_name,omitempty"`
	StepIndex            int32                  `protobuf:"varint,7,opt,name=step_index,json=stepIndex,proto3" json:"step_index,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CompensationTaskResponse) Reset() {
	*x = CompensationTaskResponse{}
	mi := &file_api_proto_workflow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompensationTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompensationTaskResponse) ProtoMessage() {}

func (x *CompensationTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workflow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompensationTaskResponse.ProtoReflect.Descriptor instead.
func (*CompensationTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_workflow_proto_rawDescGZIP(), []int{11}
}

func (x *CompensationTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CompensationTaskResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *CompensationTaskResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompensationTaskResponse) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *CompensationTaskResponse) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *CompensationTaskResponse) GetCompensationStepName() string {
	if x != nil {
		return x.CompensationStepName
	}
	return ""
}

func (x *CompensationTaskResponse) GetStepIndex() int32 {
	if x != nil {
		return x.StepIndex
	}
	return 0
}

type CompleteCompensationTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Result        []byte                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteCompensationTaskRequest) Reset() {
	*x = CompleteCompensationTaskRequest{}
	mi := &file_api_proto_workflow_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteCompensationTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteCompensationTaskRequest) ProtoMessage() {}

func (x *CompleteCompensationTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workflow_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteCompensationTaskRequest.ProtoReflect.Descriptor instead.
func (*CompleteCompensationTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workflow_proto_rawDescGZIP(), []int{12}
}

func (x *CompleteCompensationTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CompleteCompensationTaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *CompleteCompensationTaskRequest) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CompleteCompensationTaskRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CompleteCompensationTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteCompensationTaskResponse) Reset() {
	*x = CompleteCompensationTaskResponse{}
	mi := &file_api_proto_workflow_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteCompensationTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteCompensationTaskResponse) ProtoMessage() {}

func (x *CompleteCompensationTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workflow_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteCompensationTaskResponse.ProtoReflect.Descriptor instead.
func (*CompleteCompensationTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_workflow_proto_rawDescGZIP(), []int{13}
}

func (x *CompleteCompensationTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetWorkflowResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowResultRequest) Reset() {
	*x = GetWorkflowResultRequest{}
	mi := &file_api_proto_workflow_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowResultRequest) ProtoMessage() {}

func (x *GetWorkflowResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workflow_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowResultRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowResultRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workflow_proto_rawDescGZIP(), []int{14}
}

func (x *GetWorkflowResultRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type GetWorkflowResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Result        []byte                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowResultResponse) Reset() {
	*x = GetWorkflowResultResponse{}
	mi := &file_api_proto_workflow_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowResultResponse) ProtoMessage() {}

func (x *GetWorkflowResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workflow_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowResultResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowResultResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_workflow_proto_rawDescGZIP(), []int{15}
}

func (x *GetWorkflowResultResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetWorkflowResultResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetWorkflowResultResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CancelWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWorkflowRequest) Reset() {
	*x = CancelWorkflowRequest{}
	mi := &file_api_proto_workflow_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWorkflowRequest) ProtoMessage() {}

func (x *CancelWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workflow_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWorkflowRequest.ProtoReflect.Descriptor instead.
func (*CancelWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workflow_proto_rawDescGZIP(), []int{16}
}

func (x *CancelWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type CancelWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWorkflowResponse) Reset() {
	*x = CancelWorkflowResponse{}
	mi := &file_api_proto_workflow_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWorkflowResponse) ProtoMessage() {}

func (x *CancelWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workflow_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWorkflowResponse.ProtoReflect.Descriptor instead.
func (*CancelWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_workflow_proto_rawDescGZIP(), []int{17}
}

func (x *CancelWorkflowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StreamWorkflowHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamWorkflowHistoryRequest) Reset() {
	*x = StreamWorkflowHistoryRequest{}
	mi := &file_api_proto_workflow_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamWorkflowHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamWorkflowHistoryRequest) ProtoMessage() {}

func (x *StreamWorkflowHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workflow_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamWorkflowHistoryRequest.ProtoReflect.Descriptor instead.
func (*StreamWorkflowHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workflow_proto_rawDescGZIP(), []int{18}
}

func (x *StreamWorkflowHistoryRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type SendSignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSignalRequest) Reset() {
	*x = SendSignalRequest{}
	mi := &file_api_proto_workflow_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSignalRequest) ProtoMessage() {}

func (x *SendSignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workflow_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSignalRequest.ProtoReflect.Descriptor instead.
func (*SendSignalRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workflow_proto_rawDescGZIP(), []int{19}
}

func (x *SendSignalRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *SendSignalRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SendSignalRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendSignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivered     bool                   `protobuf:"varint,1,opt,name=delivered,proto3" json:"delivered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSignalResponse) Reset() {
	*x = SendSignalResponse{}
	mi := &file_api_proto_workflow_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSignalResponse) ProtoMessage() {}

func (x *SendSignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workflow_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSignalResponse.ProtoReflect.Descriptor instead.
func (*SendSignalResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_workflow_proto_rawDescGZIP(), []int{20}
}

func (x *SendSignalResponse) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

type PollSignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollSignalRequest) Reset() {
	*x = PollSignalRequest{}
	mi := &file_api_proto_workflow_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollSignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollSignalRequest) ProtoMessage() {}

func (x *PollSignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workflow_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollSignalRequest.ProtoReflect.Descriptor instead.
func (*PollSignalRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_workflow_proto_rawDescGZIP(), []int{21}
}

func (x *PollSignalRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *PollSignalRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PollSignalRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type SignalEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	TimedOut      bool                   `protobuf:"varint,3,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalEvent) Reset() {
	*x = SignalEvent{}
	mi := &file_api_proto_workflow_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalEvent) ProtoMessage() {}

func (x *SignalEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_workflow_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalEvent.ProtoReflect.Descriptor instead.
func (*SignalEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_workflow_proto_rawDescGZIP(), []int{22}
}

func (x *SignalEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignalEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignalEvent) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

var File_api_proto_workflow_proto protoreflect.FileDescriptor

const file_api_proto_workflow_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/workflow.proto\x12\bworkflow\x1a\x1fgoogle/protobuf/timestamp.proto\"L\n" +
	"\x14HeartbeatTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\"3\n" +
	"\x15HeartbeatTaskResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\x85\x02\n" +
	"\x17RegisterWorkflowRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12#\n" +
	"\rworkflow_type\x18\x02 \x01(\tR\fworkflowType\x12\x14\n" +
	"\x05steps\x18\x03 \x03(\tR\x05steps\x12-\n" +
	"\x12compensation_steps\x18\x04 \x03(\tR\x11compensationSteps\x126\n" +
	"\x17default_timeout_seconds\x18\x05 \x01(\x05R\x15defaultTimeoutSeconds\x12*\n" +
	"\x11step_max_attempts\x18\x06 \x03(\x05R\x0fstepMaxAttempts\"y\n" +
	"\x18RegisterWorkflowResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x92\x01\n" +
	"\x14StartWorkflowRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05input\x18\x02 \x01(\fR\x05input\x12\x1d\n" +
	"\n" +
	"task_queue\x18\x03 \x01(\tR\ttaskQueue\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x03R\x0etimeoutSeconds\"r\n" +
	"\x15StartWorkflowResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\"P\n" +
	"\x12StreamTasksRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"task_queue\x18\x02 \x01(\tR\ttaskQueue\"\x85\x01\n" +
	"\fHistoryEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12#\n" +
	"\ractivity_name\x18\x03 \x01(\tR\factivityName\x12\x16\n" +
	"\x06result\x18\x04 \x01(\fR\x06result\"\xb4\x01\n" +
	"\x12StreamTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05input\x18\x04 \x01(\fR\x05input\x12\x1b\n" +
	"\tstep_name\x18\x05 \x01(\tR\bstepName\x12\x1d\n" +
	"\n" +
	"step_index\x18\x06 \x01(\x05R\tstepIndex\"y\n" +
	"\x13CompleteTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x16\n" +
	"\x06result\x18\x03 \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"0\n" +
	"\x14CompleteTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xf0\x01\n" +
	"\x18CompensationTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05input\x18\x04 \x01(\fR\x05input\x12\x1b\n" +
	"\tstep_name\x18\x05 \x01(\tR\bstepName\x124\n" +
	"\x16compensation_step_name\x18\x06 \x01(\tR\x14compensationStepName\x12\x1d\n" +
	"\n" +
	"step_index\x18\a \x01(\x05R\tstepIndex\"\x85\x01\n" +
	"\x1fCompleteCompensationTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x16\n" +
	"\x06result\x18\x03 \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"<\n" +
	" CompleteCompensationTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\";\n" +
	"\x18GetWorkflowResultRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"_\n" +
	"\x19GetWorkflowResultResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x16\n" +
	"\x06result\x18\x02 \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"8\n" +
	"\x15CancelWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"2\n" +
	"\x16CancelWorkflowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"?\n" +
	"\x1cStreamWorkflowHistoryRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"d\n" +
	"\x11SendSignalRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"2\n" +
	"\x12SendSignalResponse\x12\x1c\n" +
	"\tdelivered\x18\x01 \x01(\bR\tdelivered\"i\n" +
	"\x11PollSignalRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x03R\ttimeoutMs\"X\n" +
	"\vSignalEvent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1b\n" +
	"\ttimed_out\x18\x03 \x01(\bR\btimedOut2\xf7\b\n" +
	"\x0fWorkflowService\x12Y\n" +
	"\x10RegisterWorkflow\x12!.workflow.RegisterWorkflowRequest\x1a\".workflow.RegisterWorkflowResponse\x12P\n" +
	"\rStartWorkflow\x12\x1e.workflow.StartWorkflowRequest\x1a\x1f.workflow.StartWorkflowResponse\x12K\n" +
	"\vStreamTasks\x12\x1c.workflow.StreamTasksRequest\x1a\x1c.workflow.StreamTaskResponse0\x01\x12M\n" +
	"\fCompleteTask\x12\x1d.workflow.CompleteTaskRequest\x1a\x1e.workflow.CompleteTaskResponse\x12]\n" +
	"\x17StreamCompensationTasks\x12\x1c.workflow.StreamTasksRequest\x1a\".workflow.CompensationTaskResponse0\x01\x12q\n" +
	"\x18CompleteCompensationTask\x12).workflow.CompleteCompensationTaskRequest\x1a*.workflow.CompleteCompensationTaskResponse\x12\\\n" +
	"\x11GetWorkflowResult\x12\".workflow.GetWorkflowResultRequest\x1a#.workflow.GetWorkflowResultResponse\x12Y\n" +
	"\x15StreamWorkflowHistory\x12&.workflow.StreamWorkflowHistoryRequest\x1a\x16.workflow.HistoryEvent0\x01\x12S\n" +
	"\x0eCancelWorkflow\x12\x1f.workflow.CancelWorkflowRequest\x1a .workflow.CancelWorkflowResponse\x12G\n" +
	"\n" +
	"SendSignal\x12\x1b.workflow.SendSignalRequest\x1a\x1c.workflow.SendSignalResponse\x12B\n" +
	"\n" +
	"PollSignal\x12\x1b.workflow.PollSignalRequest\x1a\x15.workflow.SignalEvent0\x01\x12P\n" +
	"\rHeartbeatTask\x12\x1e.workflow.HeartbeatTaskRequest\x1a\x1f.workflow.HeartbeatTaskResponse\x12\\\n" +
	"\x19HeartbeatCompensationTask\x12\x1e.workflow.HeartbeatTaskRequest\x1a\x1f.workflow.HeartbeatTaskResponseB8Z6github.com/yadukrishnan2004/antflow-server/api/grpc/pbb\x06proto3"

var (
	file_api_proto_workflow_proto_rawDescOnce sync.Once
	file_api_proto_workflow_proto_rawDescData []byte
)

func file_api_proto_workflow_proto_rawDescGZIP() []byte {
	file_api_proto_workflow_proto_rawDescOnce.Do(func() {
		file_api_proto_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_workflow_proto_rawDesc), len(file_api_proto_workflow_proto_rawDesc)))
	})
	return file_api_proto_workflow_proto_rawDescData
}

var file_api_proto_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_api_proto_workflow_proto_goTypes = []any{
	(*HeartbeatTaskRequest)(nil),             // 0: workflow.HeartbeatTaskRequest
	(*HeartbeatTaskResponse)(nil),            // 1: workflow.HeartbeatTaskResponse
	(*RegisterWorkflowRequest)(nil),          // 2: workflow.RegisterWorkflowRequest
	(*RegisterWorkflowResponse)(nil),         // 3: workflow.RegisterWorkflowResponse
	(*StartWorkflowRequest)(nil),             // 4: workflow.StartWorkflowRequest
	(*StartWorkflowResponse)(nil),            // 5: workflow.StartWorkflowResponse
	(*StreamTasksRequest)(nil),               // 6: workflow.StreamTasksRequest
	(*HistoryEvent)(nil),                     // 7: workflow.HistoryEvent
	(*StreamTaskResponse)(nil),               // 8: workflow.StreamTaskResponse
	(*CompleteTaskRequest)(nil),              // 9: workflow.CompleteTaskRequest
	(*CompleteTaskResponse)(nil),             // 10: workflow.CompleteTaskResponse
	(*CompensationTaskResponse)(nil),         // 11: workflow.CompensationTaskResponse
	(*CompleteCompensationTaskRequest)(nil),  // 12: workflow.CompleteCompensationTaskRequest
	(*CompleteCompensationTaskResponse)(nil), // 13: workflow.CompleteCompensationTaskResponse
	(*GetWorkflowResultRequest)(nil),         // 14: workflow.GetWorkflowResultRequest
	(*GetWorkflowResultResponse)(nil),        // 15: workflow.GetWorkflowResultResponse
	(*CancelWorkflowRequest)(nil),            // 16: workflow.CancelWorkflowRequest
	(*CancelWorkflowResponse)(nil),           // 17: workflow.CancelWorkflowResponse
	(*StreamWorkflowHistoryRequest)(nil),     // 18: workflow.StreamWorkflowHistoryRequest
	(*SendSignalRequest)(nil),                // 19: workflow.SendSignalRequest
	(*SendSignalResponse)(nil),               // 20: workflow.SendSignalResponse
	(*PollSignalRequest)(nil),                // 21: workflow.PollSignalRequest
	(*SignalEvent)(nil),                      // 22: workflow.SignalEvent
	(*timestamppb.Timestamp)(nil),            // 23: google.protobuf.Timestamp
}
var file_api_proto_workflow_proto_depIdxs = []int32{
	23, // 0: workflow.RegisterWorkflowResponse.created_at:type_name -> google.protobuf.Timestamp
	2,  // 1: workflow.WorkflowService.RegisterWorkflow:input_type -> workflow.RegisterWorkflowRequest
	4,  // 2: workflow.WorkflowService.StartWorkflow:input_type -> workflow.StartWorkflowRequest
	6,  // 3: workflow.WorkflowService.StreamTasks:input_type -> workflow.StreamTasksRequest
	9,  // 4: workflow.WorkflowService.CompleteTask:input_type -> workflow.CompleteTaskRequest
	6,  // 5: workflow.WorkflowService.StreamCompensationTasks:input_type -> workflow.StreamTasksRequest
	12, // 6: workflow.WorkflowService.CompleteCompensationTask:input_type -> workflow.CompleteCompensationTaskRequest
	14, // 7: workflow.WorkflowService.GetWorkflowResult:input_type -> workflow.GetWorkflowResultRequest
	18, // 8: workflow.WorkflowService.StreamWorkflowHistory:input_type -> workflow.StreamWorkflowHistoryRequest
	16, // 9: workflow.WorkflowService.CancelWorkflow:input_type -> workflow.CancelWorkflowRequest
	19, // 10: workflow.WorkflowService.SendSignal:input_type -> workflow.SendSignalRequest
	21, // 11: workflow.WorkflowService.PollSignal:input_type -> workflow.PollSignalRequest
	0,  // 12: workflow.WorkflowService.HeartbeatTask:input_type -> workflow.HeartbeatTaskRequest
	0,  // 13: workflow.WorkflowService.HeartbeatCompensationTask:input_type -> workflow.HeartbeatTaskRequest
	3,  // 14: workflow.WorkflowService.RegisterWorkflow:output_type -> workflow.RegisterWorkflowResponse
	5,  // 15: workflow.WorkflowService.StartWorkflow:output_type -> workflow.StartWorkflowResponse
	8,  // 16: workflow.WorkflowService.StreamTasks:output_type -> workflow.StreamTaskResponse
	10, // 17: workflow.WorkflowService.CompleteTask:output_type -> workflow.CompleteTaskResponse
	11, // 18: workflow.WorkflowService.StreamCompensationTasks:output_type -> workflow.CompensationTaskResponse
	13, // 19: workflow.WorkflowService.CompleteCompensationTask:output_type -> workflow.CompleteCompensationTaskResponse
	15, // 20: workflow.WorkflowService.GetWorkflowResult:output_type -> workflow.GetWorkflowResultResponse
	7,  // 21: workflow.WorkflowService.StreamWorkflowHistory:output_type -> workflow.HistoryEvent
	17, // 22: workflow.WorkflowService.CancelWorkflow:output_type -> workflow.CancelWorkflowResponse
	20, // 23: workflow.WorkflowService.SendSignal:output_type -> workflow.SendSignalResponse
	22, // 24: workflow.WorkflowService.PollSignal:output_type -> workflow.SignalEvent
	1,  // 25: workflow.WorkflowService.HeartbeatTask:output_type -> workflow.HeartbeatTaskResponse
	1,  // 26: workflow.WorkflowService.HeartbeatCompensationTask:output_type -> workflow.HeartbeatTaskResponse
	14, // [14:27] is the sub-list for method output_type
	1,  // [1:14] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_workflow_proto_init() }
func file_api_proto_workflow_proto_init() {
	if File_api_proto_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_workflow_proto_rawDesc), len(file_api_proto_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_workflow_proto_goTypes,
		DependencyIndexes: file_api_proto_workflow_proto_depIdxs,
		MessageInfos:      file_api_proto_workflow_proto_msgTypes,
	}.Build()
	File_api_proto_workflow_proto = out.File
	file_api_proto_workflow_proto_goTypes = nil
	file_api_proto_workflow_proto_depIdxs = nil
}
